version: 2


shared: &shared
  working_directory: ~/shorttext

  steps:
    - checkout

    - run:
        name: Apt Install
        command: |
          sudo apt-get update
          sudo apt-get install libc6
          sudo apt-get install python3-dev

    - run:
        name: Installing Miniconda and Packages
        command: |
          pip install --upgrade --user  .
          pip install --upgrade --user google-compute-engine

    - run:
        name: Run Unit Tests
        command: |
          pip install -r test_requirements.txt
          python setup.py test


jobs:
  py37:
    <<: *shared
    docker:
      - image: cimg/python:3.7

  py38:
    <<: *shared
    docker:
      - image: cimg/python:3.8

  py39:
    <<: *shared
    docker:
      - image: cimg/python:3.9

  py310:
    <<: *shared
    docker:
      - image: cimg/python:3.10


workflows:
  version: 2
  build:
    jobs:
      - py37
      - py38
      - py39
      - py310
