dist: trusty
language: python
cache:
  directories:
    - $HOME/.videoflow
matrix:
    include:
        - python: 3.6
          env: TEST_MODE=EXAMPLES_TESTS PIL=Pillow
        - python: 3.6
          env: PIL=Pillow
install:
  # code below is taken from http://conda.pydata.org/docs/travis.html
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  - travis_retry conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - source activate test-environment

  - travis_retry pip install --only-binary=numpy,scipy,pandas numpy filterpy nose scipy h5py pytest pytest-timeout pandas --progress-bar off

  # set library path
  - export LD_LIBRARY_PATH=$HOME/miniconda/envs/test-environment/lib/:$LD_LIBRARY_PATH

  - pip install -e .[tests] --progress-bar off

  # install TensorFlow (CPU version).
  - pip install tensorflow==1.13.1 --progress-bar off

  # install mkdocs
  - pip install mkdocs --progress-bar off

  # install pyux
  - pip install pyux

  - pip install flake8

before_script:
  # stop the build if there are Python syntax errors or undefined names
  - flake8 . --count --select=E9,F63,F72,F82 --show-source --statistics
  # exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
  - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

# command to run tests
script:
  - export MKL_THREADING_LAYER="GNU"
  
  - if [[ "$TEST_MODE" == "EXAMPLES_TESTS" ]]; then
      PYTHONPATH=$PWD:$PYTHONPATH py.test tests/examples_tests;
    elif [[ "$TEST_MODE" == "PEP8_DOC" ]]; then
      PYTHONPATH=$PWD:$PYTHONPATH py.test --pep8 -m pep8 -n0 && py.test tests/docs;
    else
      PYTHONPATH=$PWD:$PYTHONPATH py.test tests/ --ignore=tests/examples_tests --ignore=tests/docs;
    fi